version: '3'
services:
  db:
    image: postgres
    external_links:
        - docker-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
  app:
    depends_on:
      - db
    image: app
    ports:
      - "9191:9191"
    environment:
      - DB_HOST=docker-postgres
      - DB_PORT="5432"
      - DB_USER="test"
      - DB_PASS="test"
      - DB_NAME="app"
