version: '3'
  db:
    image: postgres
    ports:
    - "5432:5000"
    environment:
      POSTGRES_USER: "thimble"
      POSTGRES_PASSWORD: "c1oudc0w"
  app:
    build: .
    ports:
      - "8080:9000"
    depends_on:
      - db