version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5000"
    environment:
      POSTGRES_USER: "thimble"
      POSTGRES_PASSWORD: "c1oudc0w"
  app:
    image: app5
    ports:
      - "9191:9191"
    depends_on:
      - db